/** Maps English team names (wcup2026.org) to Portuguese names used in the DB */
export const WC2026_EN_TO_PT: Record<string, string> = {
  Mexico: 'México',
  'South Korea': 'Coreia do Sul',
  'Korea Republic': 'Coreia do Sul',
  'Czech Republic': 'República Tcheca',
  Czechia: 'República Tcheca',
  'South Africa': 'África do Sul',
  Canada: 'Canadá',
  Switzerland: 'Suíça',
  'Bosnia and Herzegovina': 'Bósnia e Herzegovina',
  Qatar: 'Catar',
  Brazil: 'Brasil',
  Morocco: 'Marrocos',
  Scotland: 'Escócia',
  Haiti: 'Haiti',
  USA: 'Estados Unidos',
  'United States': 'Estados Unidos',
  Australia: 'Austrália',
  Paraguay: 'Paraguai',
  Turkey: 'Turquia',
  Germany: 'Alemanha',
  'Ivory Coast': 'Costa do Marfim',
  "Côte d'Ivoire": 'Costa do Marfim',
  Ecuador: 'Equador',
  Curaçao: 'Curaçao',
  Netherlands: 'Holanda',
  Holland: 'Holanda',
  Japan: 'Japão',
  Sweden: 'Suécia',
  Tunisia: 'Tunísia',
  Egypt: 'Egito',
  Iran: 'Irã',
  Belgium: 'Bélgica',
  'New Zealand': 'Nova Zelândia',
  Spain: 'Espanha',
  Uruguay: 'Uruguai',
  'Cape Verde': 'Cabo Verde',
  'Saudi Arabia': 'Arábia Saudita',
  France: 'França',
  Norway: 'Noruega',
  Senegal: 'Senegal',
  Iraq: 'Iraque',
  Argentina: 'Argentina',
  Austria: 'Áustria',
  Algeria: 'Argélia',
  Jordan: 'Jordânia',
  Colombia: 'Colômbia',
  'DR Congo': 'RD Congo',
  'Congo DR': 'RD Congo',
  'Democratic Republic of Congo': 'RD Congo',
  Portugal: 'Portugal',
  Uzbekistan: 'Uzbequistão',
  England: 'Inglaterra',
  Ghana: 'Gana',
  Panama: 'Panamá',
  Croatia: 'Croácia',
}

export function toPortuguese(englishName: string): string {
  return WC2026_EN_TO_PT[englishName] ?? englishName
}
